-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 15:23:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw` DEFAULT CHARACTER SET utf8 ;
USE `dw` ;

-- -----------------------------------------------------
-- Table `dw`.`dim_embarcado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`dim_embarcado` (
  `id` INT NOT NULL,
  `nome_pais` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`dim_passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`dim_passageiro` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `idade` INT NOT NULL,
  `sobrevivencia` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`dim_bilhete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`dim_bilhete` (
  `id` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cabine` VARCHAR(45) NOT NULL,
  `clase` VARCHAR(45) NOT NULL,
  `tarifa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw`.`fato_sobrevivencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw`.`fato_sobrevivencia` (
  `id` INT NOT NULL,
  `passageiro` VARCHAR(100) NOT NULL,
  `bilhete` VARCHAR(45) NOT NULL,
  `embarcado` VARCHAR(45) NOT NULL,
  `dim_embarcado_id` INT NOT NULL,
  `dim_passageiro_id` INT NOT NULL,
  `dim_bilhete_id` INT NOT NULL,
  PRIMARY KEY (`id`, `dim_embarcado_id`, `dim_passageiro_id`, `dim_bilhete_id`),
  INDEX `fk_fato_sobrevivencia_dim_embarcado_idx` (`dim_embarcado_id` ASC) VISIBLE,
  INDEX `fk_fato_sobrevivencia_dim_passageiro1_idx` (`dim_passageiro_id` ASC) VISIBLE,
  INDEX `fk_fato_sobrevivencia_dim_bilhete1_idx` (`dim_bilhete_id` ASC) VISIBLE,
  CONSTRAINT `fk_fato_sobrevivencia_dim_embarcado`
    FOREIGN KEY (`dim_embarcado_id`)
    REFERENCES `dw`.`dim_embarcado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_sobrevivencia_dim_passageiro1`
    FOREIGN KEY (`dim_passageiro_id`)
    REFERENCES `dw`.`dim_passageiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_sobrevivencia_dim_bilhete1`
    FOREIGN KEY (`dim_bilhete_id`)
    REFERENCES `dw`.`dim_bilhete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;